### ISSUE TITLE
Documentation for Vue/React projects seems obsolete

### ISSUE THREAD

**Issue by xel1045** [spatie/eslint-config-spatie#3]
Since your version 2, I think we don't have to include `spatie/vue` for Vue projects:

```
{
    "extends": "spatie/vue"
}
```

**Comment by sebastiandedeyne** [comment]
Hi, we're not actively maintaining this repository anymore, I've added a note to the readme.

We've reverted to a simpler configuration, which we just set up per project.

https://github.com/spatie/blender/blob/93827c60119c86781f21fef21cfe1b23d4e4a77c/.eslintrc
